---
default:
  name: "project hortabot"
  planejado: [0, 3, 4, 6, 9, 12, 15, 17, 19, 22, 23, 25, 27, 28, 29, 29]
  realizado: [0, 4]
  esforcos: [0.1, 0.2, 0.3]
  # size = 16
  #          x     x      x      x       x      x      x      x      x      x      x      x      x      x      x     x
  datas: [18/04, 14/06, 28/06, 12/07, 26/07, 09/08, 23/08, 06/09, 20/09, 04/10, 18/10, 01/11, 15/11, 29/11, 13/12, 27/12]
...
